In [1]:
!pip install pyclustering

Collecting pyclustering
  Downloading pyclustering-0.10.1.2.tar.gz (2.6 MB)
     ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
     ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
     -------- ------------------------------- 0.5/2.6 MB 1.5 MB/s eta 0:00:02
     ------------ --------------------------- 0.8/2.6 MB 1.5 MB/s eta 0:00:02
     ---------------- ----------------------- 1.0/2.6 MB 1.4 MB/s eta 0:00:02
     -------------------- ------------------- 1.3/2.6 MB 1.4 MB/s eta 0:00:01
     ------------------------ --------------- 1.6/2.6 MB 1.4 MB/s eta 0:00:01
     ---------------------------- ----------- 1.8/2.6 MB 1.4 MB/s eta 0:00:01
     -------------------------------- ------- 2.1/2.6 MB 1.4 MB/s eta 0:00:01
     -------------------------------- ------- 2.1/2.6 MB 1.4 MB/s eta 0:00:01
     ------------------------------------ --- 2.4/2.6 MB 1.2 MB/s eta 0:00:01
     ---------------------------------------- 2.6/2.6 MB 1.2 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: scipy>=1.1.0 in c:\users\alias\anaconda3\lib\site-packages (from pyclustering) (1.17.0)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\alias\anaconda3\lib\site-packages (from pyclustering) (3.10.8)
Requirement already satisfied: numpy>=1.15.2 in c:\users\alias\anaconda3\lib\site-packages (from pyclustering) (2.4.2)
Requirement already satisfied: Pillow>=5.2.0 in c:\users\alias\anaconda3\lib\site-packages (from pyclustering) (11.1.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\alias\anaconda3\lib\site-packages (from matplotlib>=3.0.0->pyclustering) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\alias\anaconda3\lib\site-packages (from matplotlib>=3.0.0->pyclustering) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\alias\anaconda3\lib\site-packages (from matplotlib>=3.0.0->pyclustering) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\alias\anaconda3\lib\site-packages (from matplotlib>=3.0.0->pyclustering) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\alias\anaconda3\lib\site-packages (from matplotlib>=3.0.0->pyclustering) (24.2)
Requirement already satisfied: pyparsing>=3 in c:\users\alias\anaconda3\lib\site-packages (from matplotlib>=3.0.0->pyclustering) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\alias\anaconda3\lib\site-packages (from matplotlib>=3.0.0->pyclustering) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\alias\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->pyclustering) (1.17.0)
Building wheels for collected packages: pyclustering
  Building wheel for pyclustering (setup.py): started
  Building wheel for pyclustering (setup.py): finished with status 'done'
  Created wheel for pyclustering: filename=pyclustering-0.10.1.2-py3-none-any.whl size=2395133 sha256=4c021eefdec42046fe8caf0a8b13753e3db6a0cec284be31b0a407d5b3981697
  Stored in directory: c:\users\alias\appdata\local\pip\cache\wheels\82\ff\9c\fb3aedfa7966808cbd411ebca7df35bf731fe9e01c2cd699ee
Successfully built pyclustering
Installing collected packages: pyclustering
Successfully installed pyclustering-0.10.1.2

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\alias\anaconda3\Lib\site-packages)
  DEPRECATION: Building 'pyclustering' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'pyclustering'. Discussion can be found at https://github.com/pypa/pip/issues/6334
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\alias\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\alias\anaconda3\Lib\site-packages)

In [ ]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

from pyclustering.cluster.kmedoids import kmedoids
from pyclustering.utils import distance_metric, type_metric  

from sklearn import datasets
from sklearn.preprocessing import StandardScaler

In [5]:
wine = datasets.load_wine()

In [6]:
wine_df = pd.DataFrame(wine.data,columns = wine.feature_names)

In [7]:
wine_df.head()

   alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]

In [8]:
wine_df.tail()

     alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
173    13.71        5.65  2.45  ...  0.64                          1.74    740.0
174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
175    13.27        4.28  2.26  ...  0.59                          1.56    835.0
176    13.17        2.59  2.37  ...  0.60                          1.62    840.0
177    14.13        4.10  2.74  ...  0.61                          1.60    560.0

[5 rows x 13 columns]

In [9]:
wine_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: float64(13)
memory usage: 18.2 KB

In [13]:
wine_df.describe()

          alcohol  malic_acid  ...  od280/od315_of_diluted_wines      proline
count  178.000000  178.000000  ...                    178.000000   178.000000
mean    13.000618    2.336348  ...                      2.611685   746.893258
std      0.811827    1.117146  ...                      0.709990   314.907474
min     11.030000    0.740000  ...                      1.270000   278.000000
25%     12.362500    1.602500  ...                      1.937500   500.500000
50%     13.050000    1.865000  ...                      2.780000   673.500000
75%     13.677500    3.082500  ...                      3.170000   985.000000
max     14.830000    5.800000  ...                      4.000000  1680.000000

[8 rows x 13 columns]

In [11]:
scaler = StandardScaler()
x_scaler = scaler.fit_transform(wine.data)
x_scaler

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]], shape=(178, 13))

In [12]:
initial_medoids = [0,1,2]

In [16]:
import random
initial_medoids = random.sample(range(len(x_scaler)),3)

In [15]:
metric = distance_metric(type_metric.EUCLIDEAN)

kmedoids_instance = kmedoids(x_scaler,initial_medoids,metric = metric)

In [17]:
kmedoids_instance.process()

In [19]:
cluster = kmedoids_instance.get_clusters()
medoids = kmedoids_instance.get_medoids()

In [21]:
# plot the results
plt.figure(figsize=(8, 6))
for cluster in clusters:
    plt.scatter(X_scaled[cluster, 0], X_scaled[cluster, 1], label=f'Cluster {clusters.index(cluster)}')

# marks the medoids in red 

for medoid in medoids:
    plt.scatter(X_scaled[medoid, 0], X_scaled[medoid, 1], s=200, c='red', marker='X', label='Medoid')

plt.title('K-Medoids Clustering of (Wine Dataset) with PyClustering')
  

plt.legend()
plt.show()

NameError: name 'clusters' is not defined