In [1]:
import numpy as np

In [2]:
a = np.array([[2,3,4],[3,5,6],[5,8,9],[6,9,11],[7,10,13]])
a

array([[ 2,  3,  4],
       [ 3,  5,  6],
       [ 5,  8,  9],
       [ 6,  9, 11],
       [ 7, 10, 13]])

In [3]:
mean_x=np.mean(a,axis=0)
mean_x

array([4.6, 7. , 8.6])

In [4]:
x_center = a - mean_x
x_center

array([[-2.6, -4. , -4.6],
       [-1.6, -2. , -2.6],
       [ 0.4,  1. ,  0.4],
       [ 1.4,  2. ,  2.4],
       [ 2.4,  3. ,  4.4]])

In [5]:
cov_matrix = np.cov(x_center,rowvar=False)
cov_matrix

array([[ 4.3 ,  6.  ,  7.55],
       [ 6.  ,  8.5 , 10.5 ],
       [ 7.55, 10.5 , 13.3 ]])

In [6]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
eigenvalues

array([2.59637803e+01, 5.52557327e-03, 1.30694106e-01])

In [7]:
eigenvectors

array([[ 0.4066816 ,  0.90812885,  0.09955937],
       [ 0.56930735, -0.16669075, -0.80504865],
       [ 0.71449228, -0.38407836,  0.58479449]])

In [8]:
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:,sorted_indices]

In [9]:
x_transformed_1 = x_center @ eigenvectors[:,0]

In [10]:
x_transformed_2 = x_center @ eigenvectors[:,:2]

In [11]:
print(f"1. Transformed Data(3 to 1)P:-\n\n -->  {x_transformed_1}\n\n")
print(f"2. Transformed Data(3 to 2)P:-\n\n --> \n{x_transformed_2}")

1. Transformed Data(3 to 1)P:-

 -->  [-6.62126605 -3.64698519  1.0177769   3.42275041  5.82772392]


2. Transformed Data(3 to 2)P:-

 -->
[[-6.62126605  0.27128556]
 [-3.64698519 -0.06966338]
 [ 1.0177769  -0.5313071 ]
 [ 3.42275041 -0.0672074 ]
 [ 5.82772392  0.39689231]]

In [12]:
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [13]:
df = pd.read_csv('C:\AI_ML\winequality-red.csv')
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1591,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1592,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1593,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1594,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1595,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [14]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [15]:
df.tail()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1591,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1592,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1593,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1594,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1595,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [16]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000
mean,8.314160,0.527954,0.270276,2.535558,0.087120,15.858396,46.382206,0.996744,3.311917,0.656385,10.421147,5.637218
std,1.732203,0.179176,0.193894,1.405515,0.045251,10.460554,32.839138,0.001888,0.153346,0.163057,1.060371,0.807080
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.860000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996745,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997833,3.400000,0.730000,11.100000,6.000000
max,15.600000,1.580000,0.790000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,1.980000,14.000000,8.000000

In [17]:
df.isnull()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1591,False,False,False,False,False,False,False,False,False,False,False,False
1592,False,False,False,False,False,False,False,False,False,False,False,False
1593,False,False,False,False,False,False,False,False,False,False,False,False
1594,False,False,False,False,False,False,False,False,False,False,False,False
1595,False,False,False,False,False,False,False,False,False,False,False,False

In [18]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [19]:
df['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [20]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_train)

In [23]:
from sklearn.decomposition import PCA
pca = PCA(n_components=7)
x_train = pca.fit_transform(x_train)

In [24]:
x_test = pca.transform(x_test)

In [25]:
from sklearn.linear_model import LogisticRegression 
model = LogisticRegression(random_state = 0)
model.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [26]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred = model.predict(x_test)
y_pred

array([3, 8, 3, ..., 8, 8, 3], shape=(1276,))

In [27]:
matrix = confusion_matrix(y_test,y_pred)
print("matrix")

ValueError: Found input variables with inconsistent numbers of samples: [320, 1276, 320]